//
//  StyleKit.h
//  Salons
//
//  Created by Vyacheslav Dubovitsky on 30.04.15.
//  Copyright (c) 2015 A&P Media. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKit : NSObject

// Colors
+ (UIColor*)main;
+ (UIColor*)accent1;
+ (UIColor*)darkAccent;
+ (UIColor*)darkAccent50;

// Drawing Methods
+ (void)drawAddPhotoButtonWithFrame: (CGRect)frame isHighlighted: (BOOL)isHighlighted withText: (NSString*)withText;
+ (void)drawAddPhotoButtonSideWithFrame: (CGRect)frame isHighlighted: (BOOL)isHighlighted;
+ (void)drawDeletePhotoButtonWithFrame: (CGRect)frame isHighlighted: (BOOL)isHighlighted;

@end
